// apps/next/src/app/login/page.tsx
"use client";

import React, { useActionState } from "react";
import Link from "next/link";

import InputField from "@/components/InputField";
import AuthForm from "@/components/AuthForm";

import { logIn, SignInAsTestUser } from "@/api/auth/actions";

import type { IAuthFormState } from "@/api/auth/definitions";

const initialSate: IAuthFormState = {
    errors: {}
} as const;

const Page = () => {
    const [state, dispatch] = useActionState(logIn, initialSate);

    const onTestUserSignInHandler = async () => {
        await SignInAsTestUser();
    };

    return (
        <div className="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
            <AuthForm
                title='Sign in to your account'
                buttonTitle='Sign in'
                dispatch={dispatch}
            >
                <InputField
                    title="username"
                    label="Username"
                    error={state?.errors?.username?.[0]}
                    autoComplete="username"
                    isRequired={true}
                />

                <InputField
                    title="password"
                    label="Password"
                    inputType="password"
                    error={state?.errors?.password?.[0]}
                    autoComplete="current-password"
                    isRequired={true}
                />
            </AuthForm>

            <div className="flex flex-col gap-6 items-center">
                <p className="mt-10 text-center text-sm text-gray-500">
                    Don`t have account yet?{" "}

                    <Link
                        className="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
                        href="/register"
                    >
                        Create
                    </Link>
                </p>

                <button
                    className="bg-indigo-600 text-white px-3 py-1.5 text-sm font-semibold rounded-md"
                    onClick={onTestUserSignInHandler}
                >
                    Sign in as test user
                </button>
            </div>
        </div>
    );
};

export default Page;

// apps/svelteKit/src/routes/(public)/login/+page.svelte
<script lang="ts">
    import AuthForm from "$components/AuthForm/AuthForm.svelte";
    import InputField from "$components/InputField/InputField.svelte";

    import type {IAuthFormState} from "$interfaces/auth";

    export let form: IAuthFormState | null;
</script>

<div class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
    <AuthForm
        title='Sign in to your account'
        buttonTitle='Sign in'
        action="?/logIn"
    >
        <InputField
            title="username"
            label="Username"
            autocomplete="username"
            value={form?.username}
            error={form?.errors?.username?.[0]}
            required={true}
        />

        <InputField
            title="password"
            label="Password"
            inputType="password"
            autocomplete="current-password"
            value={form?.password}
            error={form?.errors?.password?.[0]}
            required={true}
        />
    </AuthForm>

    <div class="flex flex-col gap-6 items-center">
        <p class="mt-10 text-center text-sm text-gray-500">
            Don`t have account yet?{' '}

            <a
                class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
                href="/register"
            >
                Create
            </a>
        </p>

        <form>
            <button
                class="bg-indigo-600 text-white px-3 py-1.5 text-sm font-semibold rounded-md"
                formmethod="POST"
                formaction="?/testLogIn"
            >
                Sign in as test user
            </button>
        </form>
    </div>
</div>
