// apps/next/src/pages/RootPage/components/StatusSelector/StatusSelector.tsx
'use client'

import {FC, useCallback, useEffect} from "react";
import {cn} from "@/lib/utils";
import {usePathname, useSearchParams, useRouter} from "next/navigation";

import {statuses, statusesMap, titleByStatusMap, TStatusesMap} from "@/pages/RootPage/constants";

const StatusSelector: FC = () => {
    const router = useRouter()
    const pathname = usePathname()
    const searchParams = useSearchParams()

    const selectedStatus = searchParams?.get('status')

    const onStatusChange = useCallback((newStatus: TStatusesMap) => {
        const params = new URLSearchParams(String(searchParams))
        params.set('status', newStatus)

        router.push(pathname + '?' + String(params))
    }, [pathname, router, searchParams])

    useEffect(() => {
        const isStatusSelected = !statuses.includes(selectedStatus as TStatusesMap);

        if (isStatusSelected) {
            onStatusChange(statusesMap.ALL)
        }
    }, [onStatusChange, selectedStatus]);

    return (
        <div className="flex w-full h-10 mt-4 border border-gray-300 shadow-sm rounded-md">
            {statuses.map((status, index) => (
                <button
                    key={index}
                    className={cn("text-center text-gray-900 w-1/4 cursor-pointer rounded-md", {
                        'text-white font-medium bg-indigo-600 text-bold': status === selectedStatus,
                    })}
                    onClick={() => onStatusChange(status)}
                >
                    {titleByStatusMap[status]}
                </button>
            ))}
        </div>
    )
};

export default StatusSelector;

// apps/svelteKit/src/pages/RootPage/components/StatusSelector/StatusSelector.svelte
<script lang="ts">
    import {onMount} from "svelte";
    import {goto} from "$app/navigation";
    import { page } from '$app/stores';
    import {cn} from "$lib/utils";

    import {statuses, statusesMap, titleByStatusMap, type TStatusesMap} from "$pages/RootPage/constants";

    import { statusQuery } from '../../stores'

    let queryParams = $page.url.searchParams;

    const onStatusChange = (newStatus: TStatusesMap) => {
        statusQuery.set(newStatus)
        queryParams.set('status', newStatus)

        goto(`?${String(queryParams)}`)
    }

    onMount(() => {
        const isStatusSelected = !statuses.includes($statusQuery as TStatusesMap);

        if (isStatusSelected) {
            onStatusChange(statusesMap.ALL)
        }
    })
</script>

<div class="flex w-full h-10 mt-4 border border-gray-300 shadow-sm rounded-md">
    {#each statuses as status (status)}
        <button
            class={cn("text-center text-gray-900 w-1/4 cursor-pointer rounded-md", {
                'font-medium bg-indigo-600 text-bold text-white': status === $statusQuery,
            })}
            on:click={() => onStatusChange(status)}
        >
            {titleByStatusMap[status]}
        </button>
    {/each}
</div>
