// apps/svelteKit/src/pages/RootPage/components/TodosList/components/ActionsMenu/ActionsMenu.svelte
<script lang="ts">
    import { enhance } from '$app/forms';

    import {Menubar, MenubarContent, MenubarItem, MenubarTrigger} from '$components/MenuBar'
    import Icon from "$components/Icon/Icon.svelte";

    import {menuActions} from "./constants";

    import {Status} from "@prisma/client";
    import {createEventDispatcher} from "svelte";

    export let id: number;
    export let status: Status;

    const dispatch = createEventDispatcher()
    const submit = () => dispatch('submit')
</script>

<Menubar>
    <MenubarTrigger>
        <Icon
            type="ellipsisVertical"
            height={18}
            width={18}
        />
    </MenubarTrigger>

    <MenubarContent>
        {#each menuActions as {
            title,
            icon,
            className,
            statusShowCondition,
            statusToTransition,
            action
        } (title)}
            {#if !(statusShowCondition && statusShowCondition !== status)}
                <form
                    method="POST"
                    action={action}
                    use:enhance={({ formData }) => {
                        formData.append('id', String(id))
                        statusToTransition && formData.append('status', statusToTransition)

                        return async ({ update }) => {
                            await update();
                            submit()
                        }
                    }}
                >
                    <MenubarItem class={className}>
                        {#if icon}
                            <Icon
                                type={icon}
                                height={16}
                                width={16}
                            />
                        {/if}

                        <span>{title}</span>
                    </MenubarItem>
                </form>
            {/if}
        {/each}
    </MenubarContent>
</Menubar>

// apps/next/src/pages/RootPage/components/TodoList/components/ActionsMenu/ActionsMenu.tsx
"use client";

import { FC } from "react";
import { Status } from "@prisma/client";

import Icon from "@/components/Icon/Icon";
import { Menubar, MenubarContent, MenubarItem, MenubarTrigger } from "@/components/Menubar/Menubar";

import { menuActions } from "./constants";

interface IProps {
    id: number
    status: Status;
}

const ActionsMenu: FC<IProps> = ({
    id,
    status
}) => (
    <Menubar>
        <MenubarTrigger>
            <Icon
                type="ellipsisVertical"
                height={18}
                width={18}
            />
        </MenubarTrigger>

        <MenubarContent>
            {menuActions.map(({
                title,
                icon,
                className,
                statusShowCondition,
                onClick
            }, index) => {
                if (statusShowCondition && statusShowCondition !== status) {
                    return null;
                }

                return (
                    <MenubarItem
                        key={index}
                        className={className}
                        onClick={() => onClick(id)}
                    >
                        {icon && (
                            <Icon
                                type={icon}
                                height={16}
                                width={16}
                            />
                        )}

                        <span>{title}</span>
                    </MenubarItem>
                );}
            )}
        </MenubarContent>
    </Menubar>
);

export default ActionsMenu;
